twig:
    default_path: '%kernel.project_dir%/templates'

#rajouté pour rendre le formulaire meilleur en usant la documentation de symfony (Form/learn more puis faire un copier coller config/packages/twig.yaml
    form_themes: [ 'bootstrap_5_layout.html.twig' ]

when@test:
    twig:
        strict_variables: true
